### ISSUE TITLE
Add CodeCov support

### ISSUE THREAD

**Issue by ronaldtse** [plurimath/plurimath#126]
```
- name: Upload coverage reports to Codecov
  uses: codecov/codecov-action@v3
```

**Comment by CAMOBAP** [comment]
@ronaldtse should we add this for all our ruby repos?

According to https://github.com/codecov/codecov-action/issues/62 this is how we can use this in our repos

```
...
      - if: ${{ env.CODECOV_TOKEN != '' }}
        uses: codecov/codecov-action@v1
        env: 
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: coverage/.resultset.json
...
```

@ronaldtse could you please help to add `secrets.CODECOV_TOKEN` for plurimath, metanorma, relaton and probably some other our organisations
