### ISSUE TITLE
(URGENT) Number formatter still generating wrong values

### ISSUE THREAD

**Issue by ronaldtse** [plurimath/plurimath#363]
```yaml
      - geometrical-altitude: 0
        r-1: 0.0059
        e-1: 0.0082
        t-1: -62
        r-5: 0.0087
        e-5: 0.0141
        t-5: -58
        r-10: 0.0129
        e-10: 0.0209
        t-10: -55
        r-20: 0.0189
        e-20: 0.0307
        t-20: -52
```

The values are generating using this:
```
| {% if value.geometrical-altitude %} {{ value.geometrical-altitude }} {% endif %}
| {% if value.r-1 %}number:{{ value.r-1 }}[profile=iso80000]{% else %} - {% endif %}
| {% if value.e-1 %}number:{{ value.e-1 }}[profile=iso80000]{% else %} - {% endif %}
| {% if value.t-1 %}number:{{ value.t-1 }}[profile=iso80000]{% else %} - {% endif %}
| {% if value.r-5 %}number:{{ value.r-5 }}[profile=iso80000]{% else %} - {% endif %}
| {% if value.e-5 %}number:{{ value.e-5 }}[profile=iso80000]{% else %} - {% endif %}
| {% if value.t-5 %}number:{{ value.t-5 }}[profile=iso80000]{% else %} - {% endif %}
| {% if value.r-10 %}number:{{ value.r-10 }}[profile=iso80000]{% else %} - {% endif %}
| {% if value.e-10 %}number:{{ value.e-10 }}[profile=iso80000]{% else %} - {% endif %}
| {% if value.t-10 %}number:{{ value.t-10 }}[profile=iso80000]{% else %} - {% endif %}
| {% if value.r-20 %}number:{{ value.r-20 }}[profile=iso80000]{% else %} - {% endif %}
| {% if value.e-20 %}number:{{ value.e-20 }}[profile=iso80000]{% else %} - {% endif %}
| {% if value.t-20 %}number:{{ value.t-20 }}[profile=iso80000]{% else %} - {% endif %}
```

And the `iso80000` profile is:
```asciidoc
:number-presentation-profile-iso80000: group_digits=3,fraction_group_digits=3,decimal=",",group=&#x2009;,fraction_group=&#x2009;,notation=general,large_notation=scientific
```

Notice that in this table, all decimal values are rendered with extra zeros at the end:

* (0, 1%, r) 0.0059 => "0,005900"
* (1, 1%, r) 0.0442 => "0,04420"
* (0, 1% e') 0.0082 => "0,008200"

<img width="594" alt="Image" src="https://github.com/user-attachments/assets/d3e92f7c-296a-4bde-bcbf-ae98ccbae8eb" />

Non-zero decimal numbers that have a '0' as the first position at the decimal portion also sees the same problem:

```yaml
      - geometrical-altitude: 6
        r-1: 8.8
        e-1: 6.56
        t-1: 1
        r-5: 8.18
        e-5: 6.09
        t-5: 0
        r-10: 7.59
        e-10: 5.67
        t-10: -1
        r-20: 7.05
        e-20: 5.27
        t-20: -2
```

* 6.09 => "6,090"
* 7.05 => "7,050"

<img width="585" alt="Image" src="https://github.com/user-attachments/assets/a44c4f5d-2661-4bc9-957b-1f7fbee5b6e3" />
